### ISSUE TITLE
Display the block to members of specific cohorts

### ISSUE THREAD

**Issue by caiado** [learningworks/moodle-block_advnotifications#26] opened 2020-12-18 04:46 UTC
Hi,

It would be great if it was possible to selectively display the block to members of specific cohorts.

Ricardo

**Comment by zpottie** [comment] 2020-12-21 21:00
Hi @caiado - thanks for the suggestion! 😃 

This appears to be mostly a duplicate of #19 
Currently, it's not possible to _push_ notifications to certain contexts/groups/cohorts - only to show it globally or in a specific block instance. I recently added #24 features to make the plugin more flexible, which should allow more creative ways of using the plugin. One possible way (as there are **so many** different ways of using Moodle) is to restrict certain blocks to certain roles and add the notifications to the appropriate block.

Probably not exactly what you're after, but I'd like to add this feature to the plugin in the future - while keeping it easy and simple to use. Keeping it easy and simple to use is the core intention of the plugin.

However, feel free to submit a pull request or sponsor the work if it's essential to your operations and help out the community at the same time! :)

I'll mark this as a duplicate and add the reference to #19 here.

Thanks,
Zander

**Closed by zpottie** 2020-12-21 21:00 UTC
Labels: duplicate
