### ISSUE TITLE
Sitewide instance of block interferes with forgot_password.php and change_password.php

### ISSUE THREAD

**Issue by nstefanski** [learningworks/moodle-block_advnotifications#7] opened 2018-02-14 22:27 UTC
When I create an instance of this block on the front page and set **Page contexts** to "Display throughout entire site", and if the setting _block_advnotifications | enable_ is set to true, then both the forgotten password link on the front page and the forced password reset option on user accounts have errors. The former redirects back to the login page, and the latter gives an error `ERR_TOO_MANY_REDIRECTS`.

Note: I'm using the Essential theme and Moodle 3.4, some testing seems to indicate this error may only be with the Essential theme.

**Comment by Chocolate-lightning** [comment] 2018-02-16 00:17
Hi there,

I have tried to replicate the issue you are facing but I have not been able to.
Replcation steps I took:
1. Install Clean 3.4
2. Install latest adv_not block and essential theme
3. Change default site home
4. Allow guest access to site home
5. Add block to site home
6. Configure block to appear everywhere
7. Add notification to show globally to show on site home
8. Enter site on different browser and navigate with guest access

Was there a step I was missing in your set up? Do you have any other blocks installed?

Many thanks,
Matt

**Comment by nstefanski** [comment] 2018-02-19 23:20
We have a few other blocks that appear sitewide, however I was able to resolve the issue and replicate it internally just with block_advnotifications. I haven't been able to try with a totally fresh install, but otherwise here are the steps I used:

1. Install Clean 3.4
2. Install latest adv_not block and essential theme
3. Add block to site home (I left Dashboard as default, and manually navigated to the site home at http://my.site.address/?redirect-0)
4. Configure block to appear everywhere
5. Enable advanced notifications in the block's settings (the first setting here: http://dev.escoffieronline.com/admin/settings.php?section=blocksettingadvnotifications -- note, I was able to replicate without even creating a new notification, so long as notifications were enabled)
6. Create a new user with "Force password change" selected
7. In a separate browser, try to log in with the credentials you created (should receive error)
8. In a separate error, try to use the forgotten password link on the login screen (should immediately redirect you back to login screen without giving password reset options)
9. Either remove change the block to only appear on the site home page, or disable it in the settings, and repeat steps 7 and 8 (both should now work)

**Comment by Chocolate-lightning** [comment] 2018-02-27 01:50
Hi,

Thank you for the reproduction steps. I will look into this and see if there is any corrective action that needs to take place.

Regards,
Matt

**Comment by zpottie** [comment] 2018-03-12 03:03
Hi @nstefanski,

I was able to reproduce the issue and traced the cause to a rogue `require_login()` function call. I released a new version (v1.1.1 - commit 678d0ee) of the plugin which should fix it. Thanks for making me aware of the issue as is seems it wasn't limited to just the Essential theme either.

Thanks again, and it should be fixed now,
Zander

**Closed by zpottie** 2018-03-12 03:03 UTC
